# For more information: https://laravel.com/docs/sail
services:
    html.dev:
        image: nginx:latest
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./html:/usr/share/nginx/html
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    # node.dev:
    #     image: node:20-alpine
    #     entrypoint: /app/etc/bin/yarn.dev.sh
    #     ports:
    #         - "5173:5173"
    #     working_dir: /app
    #     volumes:
    #         - './:/app'
    #     tty: true
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
